logging:
  file: ./log/backend.log
  level.: WARN

banner:
  location: banner/banner.txt

server:
  context-path: /

spring:
  application:
    name: Backend
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
  profiles:
    active: development
  servlet:
    multipart:
        enabled: true
        # this is a hard limit, the actual restriction by the service/validator may be stricter
        max-file-size: 20MB
        max-request-size: 20MB



security:
  basic:
    enabled: false

management:
  info:
    git:
      mode: full
